### ISSUE TITLE
Directory Encrypt ?  Managing keys?

### ISSUE THREAD

**Issue by DSMasterson** [penghuili/Encrypt37#1]
Does Encrypt37 on iOS handle encryption of a directory (w/ sub-directories)?

If I want to setup multiple channels to various file servers, can I encrypt each channel with different keys and have Encrypt37 remember each one?  (This might be a PGP thing, but I'm still a PGP newbie)

**Comment by penghuili** [comment]
hi @DSMasterson , thanks for the questions.

1. Encrypt37 can't encrypt directories, what you can do is to zip the folder, and then you can use Encrypt37 to encrypt the zip file; (Currently there is a file size limit of 50MB, so the zip file can't be bigger than 50MB)
2. You can encrypt files with different public keys. Go to the settings tab -> Manage key pairs -> then "Add public key" in the "My friends' public keys" section. Then you can choose a public key, and all file / message will be encrypted with this public key (You can see the current active public key at top of the "Encrypt file" and "Encrypt text" screen)

Now I realised that there is no way to generate a new key pair. I can introduce a new screen in the settings.
I will post here when it's ready.

**Comment by penghuili** [comment]
Hi @DSMasterson , finally I released a new version, version 1.1.0

I added a "Key pair generator" screen on the settings screen. Hope this helps

I will close this issue, let me know if you need more help
