### ISSUE TITLE
is it possible to create the expo supported key pair generation npm package from you work?

### ISSUE THREAD

**Issue by starfreck** [penghuili/Encrypt37#2]

**Comment by penghuili** [comment]
Hi @starfreck , I use the react-native-fast-openpgp (https://github.com/jerson/react-native-fast-openpgp) lib for the encryption and decryption part. It's already a npm package.

I haven't used expo before, but I guess you can use react native lib within expo project

**Comment by starfreck** [comment]
I was able to add react-native lib within the expo project using [this](https://docs.expo.dev/development/create-development-builds/). I used [react-native-rsa-native](https://www.npmjs.com/package/react-native-rsa-native) and it is working well on Android.

Install the react-native lib within expo using  the below command:

`npx expo install <react-native-lib>`
